- hosts: 127.0.0.1
  connection: local
  tasks:
  - add_host: hostname=deploy
              ansible_ssh_host={{ deploy_server }}
              ansible_ssh_user={{ deploy_user }}
              ansible_ssh_pass={{ deploy_password }}
              ansible_sudo_pass={{ deploy_password }}
  - apt: name=sshpass state=present
  - file: dest=~/.ssh state=directory
  - shell: ssh-keyscan -H {{ deploy_server }} >> ~/.ssh/known_hosts

- hosts: deploy
  sudo: yes
  vars:
    project: template
    container: template_container
    registry: registry.transparent.com
    tag: '{{ version }}'
    image: '{{ project }}'
    i: '{{registry}}/{{ image }}:{{ tag }}'
    ports: 8080:8000

  tasks:
  - name: Checking if the "{{ container }}" container exists
    shell: docker inspect {{ container }} | grep Id | cut -d '"' -f 4
    register: container_id
    when: container is defined

  - name: Pulling the newest image from the repository
    command: docker pull {{ i }}
    when: tag != '0.0.0-vagrant'

  - name: Stopping the "{{ container }}" container
    command: docker stop {{ container }}
    when: container_id.stdout != ""

  - name: Removing the "{{ container }}" container
    command: docker rm --force=true --volumes=true {{ container }}
    when: container_id.stdout != ""

  - name: Running the "{{ container }}" container
    command: docker run --detach=true
                        --restart=always
                        --name={{ container }}
                        --publish={{ ports }}
                        {{ i }}