- hosts: localhost
  connection: local
  tasks:
  - pip: requirements={{ playbook_dir }}/{{ item }}
         virtualenv={{ playbook_dir }}/v
         extra_args="--trusted-host 192.168.254.81"
    with_items:
    - requirements-cpython.txt
    - test-requirements-cpython.txt
